# Generated by Django 4.2.2 on 2024-05-16 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('upload', '0005_remove_profile_profile_picture_profile_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(default='/profile_pics/default.png', upload_to='profile_pics'),
        ),
    ]
