# Generated by Django 4.2.2 on 2024-05-24 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('upload', '0007_alter_profile_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(default='/profile_pics/default.jpg', upload_to='profile_pics'),
        ),
    ]
